from enum import Enum


class OptimizationObjective(Enum):
    PATH_SCORE = 0,
    ENCOUNTERED_OBSTACLES = 1,
    PATH_LENGTH = 2,
    PATH_SMOOTHNESS = 3,
    OBSTACLE_PROXIMITY = 4,
    OPTIMAL_FLIGHT_HEIGHT = 5,
    HEIGHT_DIFFERENCE = 6,
    OPTIMAL_HEIGHT_DEVIATION = 7,
    FUEL_CONSUMPTION = 8
